AccessibleForAll/AccessibleWebDev

- components/Nav/NavItem.tsx
- stories/NavItem.stories.tsx
add an skeleton for the storybook entry of NavItem
Example page
Example page with lighthouse test
Closes #168 
- [no] I ran the app and tested it locally to verify that it works as expected.
- [98%] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
I need an hint. This codes is not valid in my mind but i dont have an idea for an page (IPage). 
Additionally the lighthouse report meets only 98% for a11y. But this is the second problem. 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [issue168] create storybook skeleton of NavItem

- components/MaintainerCard/MaintainerCard.tsx
- data/maintainers.ts
- pages/about.tsx
Moved maintainer data into it's own file and created a new IMaintainer type which can be used in both About page and Maintainer Card component. Renamed maintainerData to currentMaintainerData in case we have maintainers that leave in the future then a pastMaintainderData array can be added too.
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Refactor maintainer data and types into own file

- stories/MaintainerCard.stories.tsx
Missed updating the MaintainerCard story args the other day in the refactor
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/203"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: update args to take correct props in MaintainerCard story

- components/MaintainerCard/MaintainerCard.tsx
- pages/about.tsx
The recent PR to update interfaces and props accidentally broke the about page. This PR fixes the props in MaintainerCard so that the about page works again.
> Fix: Update props in maintainerCard component

- .eslintrc.json
- stories/Header.stories.tsx
- stories/MaintainerCard.stories.tsx
- stories/NavItem.stories.tsx
- stories/NavPrimary.stories.tsx
- stories/NavPrimaryMobile.stories.tsx
The updated naming conventions for interface props had been missed in the stories, causing the app not to build.
> Fix: Update interface names in storybook files

- components/CodeBlock/CodeBlock.tsx
* Added wrapLongLines prop in SyntaxHighlighter Element
* Improves code readability and responsiveness for Mobile Devices
<p align="center">
</p>
Closes #264 
* The Extension used to showcase those screenshots is [Mobile Simulator]((https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk)
* I have a bit of feeling to check for the horizontal scroll that persists after using wrapLongLines prop.
> using wraplongLines prop for mobile responsiveness

- .eslintrc.json
- components/CodeBlock/CodeBlock.tsx
- components/PageUpdated/PageUpdated.tsx
- components/ThemeSwitcher/ThemeSwitcher.tsx
- pages/404.tsx
- pages/[content].tsx
- pages/about.tsx
- pages/index.tsx
This PR Includes lint error messages fixes
- Forbidden non-null assertion: [referred documentation](https://typescript-eslint.io/rules/no-non-null-assertion/), check the correct example
- 't' is assigned a value but never used: [referred documentation](https://eslint.org/docs/latest/use/configure/rules#using-configuration-comments-1) + Intellisense Suggestion ( I was receiving about 4 console logs each time for different content being mounted)
- Type Alias name `TCodeLanguage` must match one of the following formats StrictPascalcase: small typo fix
- 'styles' is defined but never used: styles is being referred from `PageUpdated.module.css` which is currently empty, so i removed its declaration for time being
- React Hook useEffect has a missing dependency `handleThemeSwitcherKB`: removing …
> [FIX] address lint error messages

- components/WorkInProgress/WorkInProgress.tsx
Changed the href of the "Let us know what information you're looking for" link in the WorkInProgress component. It now leads to the Discussions page (https://github.com/AccessibleForAll/AccessibleWebDev/discussions), rather than the main page of the repo. 
Closes #277
N/A
> Change link in WorkInProgress component to Github Discussions

- components/CodeBlock/CodeBlock.module.css
- components/CodeBlock/CodeBlock.tsx
- components/CopyCodeBlock/CopyCodeBlock.tsx
- components/CopyCodeBlock/copyCodeBlock.module.css
- styles/globals.css
Added a copy and paste button to code snippets. The button's symbol will change on click. It will display "copy" text on hover and focus and "copied" on click. Is aria-labelled so should also be accessible for screen-readers. Have tested pages with Axe Devtools and found no issues.
Closes #256
> add: copy code block button to code snippet sections

- components/ContentTemplates/BreadcrumbsTemplate.tsx
On the Breadcrumbs page, under the Other Resources heading, I changed the href of the last link (Gov.uk Design System - Breadcrumbs) to https://design-system.service.gov.uk/components/breadcrumbs/, so that it leads to the correct site. 
Closes #279 
> Fix Gov.uk Design System link on Breadcrumbs page

- components/ContentTemplates/HeadingsTemplate.tsx
Changed **WCAGCriteria** in **Accessible Headings** page, list style to normal template for uniform theme.
https://github.com/AccessibleForAll/AccessibleWebDev/issues/283#issue-1680158408
Closes #283 
> Changed WCAGCriteria list style to normal template

- components/NavPage/NavPage.tsx
Replaced NextJS `Link`  with HTML `a` to fix the onfocus issue.
Closes #292 
We should add some visual style to communicate to the user they have to jump to a specific section on the `tab`
> Replaced nextjs Link with HTML a

- components/CodeBlock/CodeBlock.tsx
Added a ref to the Pre block in the react syntax highlighter so that scrollbars can be detected. Adds a tab index when scrollbars are present in order to allow keyboard users to scroll horizontally.
Closes #306 
> Add keyboard accessibility to code block

- components/CodeBlock/CodeBlock.tsx
- components/CopyCodeBlock/CopyCodeBlock.tsx
Have renamed the import of style to styles in import to be consistent with other imports.
NA
Closes #335 
NA
> Rename style to styles in import

- components/Footer/Footer.tsx
Footer links like "Become a contributor" and "Support us" are supposed to open in same tab. But current production version have open in new tab icon beside them which is misleading. This PR includes the changes to remove these icons from these 2 links
Before -
After - 
Closes #341 
> fix: removed redundant 'open in new tab' icons from links in footer

- components/Nav/NavItem.tsx
Added aria-current to anchor tags in NavItem component. if link is active then, set the value of aria-current to be "page" else set it to false.
Closes #343
> fix: Nav link state for screen readers

- components/Nav/NavPrimary.module.css
added css color property on nav link item in hover state to be of value var(--text)
Closes #351
> fix: color contrast of active nav link item when hovered

- data/tipsOfTheDay.ts
> change the link in Use Semantic HTML

- components/ContentTemplates/ChartsTemplate.tsx
- data/pageNavigationLists.ts
This PR adds content about charts
Closes #374 
This is still a work in progress
> feat: add chart

- components/ContentTemplates/ButtonsTemplate.tsx
- components/ContentTemplates/LinksTemplate.module.css
- components/ContentTemplates/LinksTemplate.tsx
- data/pageNavigationLists.ts
I added punctuation(support,) to the sentence "An empty alt attribute has the most wide-spread support so that should be your go-to choice when using icons." for better readability.
Closes #367 
> added puncuation

- components/ContentTemplates/ButtonsTemplate.tsx
- components/ContentTemplates/LinksTemplate.tsx
- data/pageNavigationLists.ts
This is an improved version of PR #390. Read [the Description section](https://github.com/AccessibleForAll/AccessibleWebDev/pull/390) for context.  
Closes #386 
N/A
> feat: add Touch Target Minimum sections to Links and Button pages

- components/Header/Header.tsx
- components/SkipLink/SkipLink.module.css
- styles/globals.css
> Update to work with dynamic types on iOS

- README.md
- components/Header/Header.tsx
- components/SkipLink/SkipLink.module.css
- styles/globals.css
> release-2024-11-10
