AccessibleForAll/AccessibleWebDev

components/Header/Header.module.css
components/Header/Header.tsx
components/Nav/NavPrimary.module.css
components/ThemeSwitcher/ThemeSwitcher.module.css
components/ThemeSwitcher/ThemeSwitcher.tsx
styles/globals.css

Added a theme toggle with three possibilities: system settings, light mode and dark mode. The toggle is fully functional with keyboard.

Add theme toggle

---

components/ContentTemplates/LinksTemplate.tsx
data/pages.ts
pages/[content].tsx

This creates LinksTemplate component, adds it to ContentPage, and adds template data to config file.
Closes #28

Add LinksTemplate component

---

components/ContentTemplates/FormsTemplate.tsx
data/pages.ts
pages/[content].tsx

Add FormsTemplate.tsx

---

README.md

resolved issue #20
Gitpod badge added at the bottom of the Readme file

Updated README.md file: Gitpod badge added

---

components/ContentTemplates/TablesTemplate.tsx
data/pages.ts
pages/[content].tsx

Followed as per the instructions and added TablesTemplate component. 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/45"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add tables template

---

components/ContentTemplates/MenusTemplate.tsx
data/pages.ts
pages/[content].tsx

Closes issue #23 
The steps have been followed. The file has been added. Changes in other files have been made.
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/48"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

File: MenusTemplate.tsx file added

---

components/ContentTemplates/ButtonsTemplate.tsx
data/pages.ts
pages/[content].tsx

Created ButtonsTemplate file and corresponding changes have been made.
Closes issue #25 
Thank you for the opportunity.
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/55"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added ButtonsTemplate

---

components/ContentTemplates/NavigationTemplate.tsx
data/pages.ts
pages/[content].tsx

Closes issue #22 
The steps have been followed. The file has been added. Changes in other files have been made. 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/43"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add NavigationTemplates

---

components/Layout/Layout.tsx
components/SkipLink/SkipLink.module.css
components/SkipLink/SkipLink.tsx

Add a SkipLink component to skip to the main content.
This PR will solve issue #16 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/58"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add SkipLink component

---

components/ContentTemplates/AlertsTemplate.tsx
data/pages.ts
pages/[content].tsx

add alertsTemplate #26

---

components/ThemeSwitcher/ThemeSwitcher.tsx
customHooks/useOnClickOutside.ts
package.json
yarn.lock

- Add `usehooks-ts` package
- Add a custom hook to handle clicks outside of a component
- Use the custom hook in the ThemeSwitcher component
Closes #12 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/73"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Theme Switcher should close when someone clicks outside of the component

---

components/ContentTemplates/ModalsTemplate.tsx
data/pages.ts
pages/[content].tsx

Close: #27 
Changes made:
1. Added ModalTemplate.tsx fle
2. Import & add the ModalTemplate in Layout tag 
3. Add ModalTemplate to the config file.
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/65"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Issue 27 add modeltemplate component

---

components/WorkInProgress/WorkInProgress.tsx

Added WorkInProgress with the necessary details
And committed only specific files as mentioned.
- [ ✔] I have performed a self-review of my code.
- [ ✔] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/82"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added WorkInProgress

---

CONTRIBUTING.md
package.json
yarn.lock

- Installed next-i18next
- Installed react-syntax-highlighter
- Updated contributing.md with installed package info

Install packages

---

next.config.js

Added the required i18n config from #85 
Closes: #85 
I'm not sure about the `en` locale :
* English in the US is `en-US`
* English in Britain is `en-EN`
Should we update?

chore(i18n): add i18n config in `next.config.js`

---

components/ContentTemplates/AnimationsTemplate.tsx

This PR adds the `WorkInProgress`component to the `AnimationsTemplate`
closes #93 
N/A
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Set WorkInProgress in AnimationsTemplate

---

data/pages.ts

issue #111 fixed by change of alphabethic order in page.ts
none
#111 (https://github.com/AccessibleForAll/AccessibleWebDev/issues/111)
I am not familar with yarn. i have run yarn install and yarn build and yarn start -> it works fine at localhost:3000
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/114"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[issue111] c section moved after b section

---

.gitignore

add .idea and .yarn folder to .gitignore file
#115 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[issue115] .idea and .yarn folders ignored for check in

---

components/ContentTemplates/ButtonsTemplate.tsx

This PR adds the WorkInProgress to the ButtonsTemplate
closes #98 
N/A
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/117"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Set WorkInProgress in ButtonsTemplate

---

components/ContentTemplates/TablesTemplate.tsx

placeholder replaced by WIP tag
#109 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[issue109] placeholder replaced by WIP tag

---

components/ContentTemplates/ModalsTemplate.tsx

Imported the WIP component to the ModalsTemplate component.
#106 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Imported WIP to modals template

---

components/ContentTemplates/ListsTemplate.tsx

Imported WorkInProgress to Lists template
Closes #104 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/121"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Imported WIP to lists template 

---

components/ContentTemplates/ImagesTemplate.tsx

This PR adds the WorkInProgress component into the ImagesTemplate 
Closes #102 
None
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/125"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Feat: Import WorkInProgress to images template

---

components/ContentTemplates/LinksTemplate.tsx

Imported WOrkInProgress form the WorkInProgress Folder and renamed the "LinksTemplate" div to WorkInProgress.
Closes #103
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Import wip to links template

---

components/ContentTemplates/FormsTemplate.tsx

Closes #99
https://github.com/AccessibleForAll/AccessibleWebDev/issues/99#event-7545484241
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

placeholder replaced by WIP tag

---

components/ContentTemplates/IconsTemplate.tsx

Added WorkInProgress component into the IconsTemplates.tsx, Resolves issue #101 
This resolves issue #101 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/126"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added WIP component to iconsTemplate

---

components/ContentTemplates/HeadingsTemplate.tsx

Added WorkInProgress component into HeadingsTemplate.tsx, this resolves issue #100 
Closes #100 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/127"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added WIP component into HeadingsTemplate

---

components/ContentTemplates/BreadcrumbsTemplate.tsx

Imported WIP componenet into BreadcrumbsTemplate.tsx, which resolves issue #97 
Closes #97
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/128"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Imported WIP into breadcrumbs

---

styles/globals.css

Changes made on lines 9 and 20
previously : --dark: #000;
now : --dark: #1c1c1c;
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update --dark variable color in global css

---

pages/about.tsx

Adding an abouts page as per request in #139 
#139 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/143"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding the abouts page

---

components/Footer/Footer.tsx

Added about link to footer
#147 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add about link (close #147)

---

components/ContentTemplates/VideoTemplate.tsx

Imported the WorkInProgress component to the Video template component
#110 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Imported WIP component to Video template

---

components/ContentTemplates/CaptchasTemplate.tsx

This adds the WorkInProgress component to the captchas template
Issue #95 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/153"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updates captchas template 

---

components/ContentTemplates/AudioTemplate.tsx

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/152"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Import WIP component into AudioTemplate

---

components/ContentTemplates/ChartsTemplate.tsx

#96 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

importeed work in progress into charts template

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: FaithKovi <faithkovivera@gmail.com>
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/158"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Modify pull request template

---

stories/Footer.stories.tsx

added footer story to storybook
Closes #165 
> just a question: what is storybook and what's the purpose of it to be used?
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added Footer story

---

components/Footer/Footer.tsx

Added `&nbsp;` to fix space issue
Closes #175 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix missing space

---

components/Nav/NavPrimaryMobile.tsx
stories/NavPrimaryMobile.stories.tsx

created NavPrimaryMobile story
Add NavPrimaryMobile story #167 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Primary Nav Mobile Story

---

.storybook/main.js
package.json
yarn.lock

I installed the accessibility extension for storybook ts following the instruction on storybook which were provided in the issue.
**Storybook run with yarn storybook in browser**
**before**
**after**
`.storybook/main.js file`
**before**
**after**
Closes #171
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Install accessibility add on in Storybook

---

components/SkipLink/SkipLink.tsx
stories/SkipLink.stories.tsx

created skiplink story
Add skiplink story #164 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add skiplink story

---

components/Footer/Footer.module.css

Made the content in the footer align with the horizontal line above it.
Closes #178 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Aligned the footer content

---

components/Nav/NavPrimary.tsx
stories/NavPrimary.stories.tsx

I added a Story called Primary Nav to the storybook. Additionally updated the component NavPrimary.tsx to export const NavPrimary and later added handleNavClick to it.
Closes #166
Hello dear maintainers. Could you please check my PR and merge it or let me know, what needs to be changed? Thank you for your support and your patience. I did manual tests and ran yarn dev and yarn storybook and all seems to run smoothly. 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Primary Nav Storybook

---

components/MaintainerCard/MaintainerCard.tsx
pages/about.tsx

Added an array of maintainer data that can be used for the maintainer cards
Closes #
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/188"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add maintainer data

---

stories/WorkInProgress.stories.tsx

I added the story called WorkInProgress.stories.tsx to the storybook.
Closes #163
Hello dear maintainers. Could you please check my PR and merge it or let me know, what needs to be changed? Thank you for your support and your patience. I did manual tests and ran yarn dev and yarn storybook and all seems to run smoothly.
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/187"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added the story WorkInProgress.stories.tsx to the storybook

---

components/ThemeSwitcher/ThemeSwitcher.tsx
components/ThemeSwitcher/themes.ts
package.json
pages/_app.tsx
yarn.lock

Prevent flickering of dark mode.
Closes #182 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix dark mode flicker

---

components/ContentTemplates/NavigationTemplate.tsx

issue #107 fixed by add working in progress tag within navigation template
Closes #107 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/191"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[issue#107] navigation template filled with working in progress tag

---

components/Footer/Footer.tsx

- `Github` -> `GitHub`.
- Feel free to mark as `invalid` as this is a very simple fix that shouldn't count for Hacktoberfest.
Closes #

chore: `Github` -> `GitHub`

---

components/ContentTemplates/MenusTemplate.tsx

Import the WorkInProgress Component into the menus template and render the component instead of the current div and placeholder section.
Closes #105
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Import WIP to menus template

---

components/MaintainerCard/MaintainerCard.module.css

amended the margin tag within the MaintainerCard section of the css file
Closes #192 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/198"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Maintain card

---

pages/[content].tsx

Fixed the piece of code to import the component
Closes #234 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix ImagesTemplate import

---

components/ContentTemplates/AlertsTemplate.tsx
components/ContentTemplates/AnimationsTemplate.tsx
components/ContentTemplates/AudioTemplate.tsx
components/ContentTemplates/BreadcrumbsTemplate.tsx
components/ContentTemplates/ButtonsTemplate.tsx
components/ContentTemplates/CaptchasTemplate.tsx
components/ContentTemplates/ChartsTemplate.tsx
components/ContentTemplates/FormsTemplate.tsx
components/ContentTemplates/HeadingsTemplate.tsx
components/ContentTemplates/IconsTemplate.tsx
components/ContentTemplates/LinksTemplate.tsx
components/ContentTemplates/ListsTemplate.tsx
components/ContentTemplates/MenusTemplate.tsx
components/ContentTemplates/ModalsTemplate.tsx
components/ContentTemplates/NavigationTemplate.tsx
components/ContentTemplates/PaginationTemplate.tsx
components/ContentTemplates/TablesTemplate.tsx
components/ContentTemplates/VideoTemplate.tsx
components/Footer/Footer.tsx
components/Layout/Layout.tsx
components/WorkInProgress/WorkInProgress.tsx
pages/404.tsx

Removed the React imports from /components and /pages except in the cases described.
Closes #231 
- [✅] I have performed a self-review of my code.
- [✅] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [✅] I ran the app and tested it locally to verify that it works as expected.
- [✅] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/236"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fixed Remove import React from react

---

components/Header/Header.tsx
components/Layout/Layout.tsx
components/MaintainerCard/MaintainerCard.tsx
components/Nav/NavItem.tsx
components/Nav/NavPrimary.tsx
components/Nav/NavPrimaryMobile.tsx
pages/about.tsx

added I at the start of every interface
Closes #232 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add capital I at the start of every interface

---

.eslintrc.json
CODING_STANDARDS.md
CONTRIBUTING.md
components/ThemeSwitcher/ThemeSwitcher.tsx
package.json
yarn.lock

- added a coding standards page
- enforced naming convention
Closes #227 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/240"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add coding standards page

---

components/ContentTemplates/AlertsTemplate.tsx
components/ContentTemplates/AnimationsTemplate.tsx
components/ContentTemplates/AudioTemplate.tsx
components/ContentTemplates/BreadcrumbsTemplate.tsx
components/ContentTemplates/ButtonsTemplate.tsx
components/ContentTemplates/CaptchasTemplate.tsx
components/ContentTemplates/ChartsTemplate.tsx
components/ContentTemplates/FormsTemplate.tsx
components/ContentTemplates/HeadingsTemplate.tsx
components/ContentTemplates/IconsTemplate.tsx
components/ContentTemplates/LinksTemplate.tsx
components/ContentTemplates/ListsTemplate.tsx
components/ContentTemplates/MenusTemplate.tsx
components/ContentTemplates/ModalsTemplate.tsx
components/ContentTemplates/NavigationTemplate.tsx
components/ContentTemplates/PaginationTemplate.tsx
components/ContentTemplates/TablesTemplate.tsx
components/ContentTemplates/VideoTemplate.tsx
pages/[content].tsx

Removed default exports from components and added named exports
Closes #230 
<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Remove default exports from components and add named exports

---

components/Header/Header.tsx
components/Layout/Layout.tsx
components/MaintainerCard/MaintainerCard.tsx
components/Nav/NavItem.tsx
components/Nav/NavPrimary.tsx
components/Nav/NavPrimaryMobile.tsx
pages/[content].tsx
pages/about.tsx

made all props consistent
Closes #229 

Make props import consistent

---

components/MaintainerCard/MaintainerCard.module.css

Updated color to align with dark and light modes

---

components/Footer/Footer.module.css
components/Footer/Footer.tsx

added icons to external links in footer
Closes #245 

Add icons to external links in footer

---

components/TipOfTheDay/TipOfTheDay.module.css
components/TipOfTheDay/index.tsx
pages/index.tsx
stories/TipOfTheDay.stories.tsx

created a card component for the `tip of the day` feature and added a corresponding story aswell.
Closes #252

Add Tip of the day component & story

---

yarn.lock

Update packages with minor and patch changes to the most recent updates.

Update outdated packages with minor and patch changes

---

.github/workflows/appreciation.yml

Add appreciation yaml file

---

components/ThemeSwitcher/ThemeSwitcher.tsx
customHooks/useOnClickOutside.ts

This Pull request fixes the Theme Picker Toggle.
Closes #290

fixed theme toggle

---

pages/_app.tsx

Adding open graph meta tags to the head
Closes #

Feat: Add open graph metatags

---

components/TipOfTheDay/TipOfTheDay.module.css
components/TipOfTheDay/index.tsx
data/tipsOfTheDay.ts
pages/index.tsx

- Used already avilable tipoftheday component to display on homepage
- Created  hard coded 7 tips in `data/tipsOfTheDay.js`
- Updated the component to render random tip from the data
- Added CSS to make it 100% on mobile screen
Closes #249 

component "tip of the day" added to homepage with random tip  

---

components/CodeBlock/CodeBlock.module.css
components/CodeBlock/CodeBlock.tsx

1. CSS changes
2. Component code change 
to make the code block responsive
Mobile view: 
Desktop View
Closes #282 

Code block responsive

---

components/TemplateSection/TemplateSection.module.css
components/TemplateSection/TemplateSection.tsx
styles/globals.css

Move the `.infoSection` css class to TemplateSection.module.css
Closes #317

Refactor TempleteSection css

---

styles/globals.css

Added Noto Sans font (https://fonts.google.com/noto/specimen/Noto+Sans#styles) 
Closes #314 314

Style: Added Noto Sans font

---

components/Footer/Footer.module.css

I have updated the spacing between links in the footer for mobile devices.
Closes #312

update list-item spacing

---

components/PageUpdated/PageUpdated.module.css
components/PageUpdated/PageUpdated.tsx
styles/globals.css

I have shifted PageLastUpdated class from global.css to PageLastUpdated.module.css. Please check the commits and review it
Closes #316 
- [yes ] I have performed a self-review of my code.
- [yes ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [yes ] I ran the app and tested it locally to verify that it works as expected.
- [ no] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 

Page last updated

---

CONTRIBUTING.md

update contributing.md file

---

components/Header/Header.module.css
components/PageUpdated/PageUpdated.module.css
components/SkipLink/SkipLink.module.css
components/ThemeSwitcher/ThemeSwitcher.module.css

fix issues with skiplink that were missed in previous release

release-2023-07-15.2

---

components/NavPage/NavPage.module.css

Issue #348
The top and bottom margins are set to be 14 px each ...

Fix margin top&bottom 14px

---

components/ContentTemplates/AudioTemplate.tsx
data/pageNavigationLists.ts
pages/docs/Style Guide.md

This PR is finishing the audio page. 
Closes #358 

feat: add content about audio

---

components/ContentTemplates/AudioTemplate.tsx
data/pageNavigationLists.ts
data/tipsOfTheDay.ts
pages/docs/Style Guide.md
styles/globals.css

release-2023-10-07.1

---

.gitpod.yml
CONTRIBUTING.md

Chore: Update references from yarn to npm

---

README.md

no issue
Closes #
- enhanced the readme.md and added a link to the website. 
- added a features section.
just to acknowledge, I used AI to help me write the new file but I reviewed it, removed the unnecessary parts, and added my personal touch.

docs(readme): improve README.md for clarity, structure, and engagement
